# Generated by Django 3.0.5 on 2020-04-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFname', models.CharField(max_length=50)),
                ('userLname', models.CharField(max_length=50)),
                ('userMobile', models.IntegerField()),
                ('userAddress', models.CharField(max_length=200)),
                ('userPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
