# Generated by Django 3.0.5 on 2020-04-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userUsername',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
