# Generated by Django 3.0.5 on 2020-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccess', '0003_auto_20200429_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
