# Generated by Django 3.0.5 on 2020-04-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0002_auto_20200426_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='offer',
        ),
        migrations.AlterField(
            model_name='item',
            name='hasStock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='hasSubcat',
            field=models.BooleanField(default=False),
        ),
    ]
