# Generated by Django 3.0.5 on 2020-04-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0003_auto_20200426_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemImage',
            field=models.ImageField(default=None, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
