# Generated by Django 3.0.5 on 2020-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0005_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='catType',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
