# Generated by Django 3.0.5 on 2020-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0006_catagory_cattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='defaultVarient',
            field=models.CharField(default='1 Kg.', max_length=20),
            preserve_default=False,
        ),
    ]
