# Generated by Django 3.0.5 on 2020-05-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0010_auto_20200430_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
