# Generated by Django 3.0.5 on 2020-05-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0015_userorders_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorders',
            name='order_id',
        ),
    ]
