# Generated by Django 3.0.5 on 2020-05-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0016_remove_userorders_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='user_id',
            new_name='order_id',
        ),
    ]
