# Generated by Django 3.0.5 on 2020-05-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0017_auto_20200508_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='ammount',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
