# Generated by Django 3.0.5 on 2020-05-08 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0018_userorders_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorders',
            name='status',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
