# Generated by Django 3.0.5 on 2020-05-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0020_orderdetails_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='user_id',
        ),
    ]
