# Generated by Django 3.0.5 on 2020-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0023_remove_orderdetails_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorders',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
