# Generated by Django 3.0.5 on 2020-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0024_auto_20200510_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='total_items',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
